### ISSUE TITLE
Dom cloning Error in FireFox 5.0 and Chrome 14.0

### ISSUE THREAD

**Issue by hyperhtml** [cemerick/arbor#2]
Both browsers have exceptions in Kernel.js on about the same line ( with the same issue).
Chrome was working up until the latest update.

Firefox's Error is:
The object could not be cloned." code: "25 - line 53
    {timeout:Math.ceil(params.timeout)}) })

Chrome's Error is:
Uncaught Error: DATA_CLONE_ERR: DOM Exception 25 - line 51
    _physics.postMessage({type:"physics",

**Comment by cemerick** [comment]
I don't have Chrome 14, but Firefox 3.6.x and Firefox 5 both appear to work well here (as tested at http://www.clojureatlas.com/org.clojure:clojure:1.2.0?guest=t).

Without seeing code examples, speculating on the cause is tough.  Perhaps you're adding app-level data to the arbor nodes directly, instead of using the provided .data slot?

**Comment by hyperhtml** [comment]
There seems to be a terminationFn that is being passed into the objmerge function and it doesn't like it...
